app = "cryptobot-azkh-a"

[build]
  image = "python:3.11"

[env]
  PYTHONUNBUFFERED = "TRUE"
  
[deploy]
  command = "python main.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
